"""Add quantity and unit to Product model

Revision ID: 49a9c95d27c7
Revises: cb8aab6e9800
Create Date: 2024-07-30 14:04:33.157768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a9c95d27c7'
down_revision = 'cb8aab6e9800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=False, server_default='unit'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
